### ISSUE TITLE
trained weights baidu link not working/breaking

### ISSUE THREAD

**Issue by ashishkr23** [yuanyuanli85/FashionAI_KeyPoint_Detection_Challenge_Keras#4]
Thanks @yuanyuanli85 for the great work.
This is going to sound really dumb, but i am finding it very difficult to down the trained weights from Baidu. It seems to break and does not resume. I have searched a lot for a way to get it going but haven't been success-full.
Would really appreciate if you could host the weight anywhere else (dropbox/google drive/aws).
Thanks

**Comment by yuanyuanli85** [comment]
Let me upload it to google drive. Will update the readme once it is done. Hope i can make it done within 2days.

**Comment by ashishkr23** [comment]
Thanks a lot for the prompt reply.

**Comment by yuanyuanli85** [comment]
Done. Please check commit 483988c

**Comment by ashishkr23** [comment]
Thank a lot .

**Comment by ashishkr23** [comment]
Hi , this still does not include the link to google drive .Thanks

**Comment by yuanyuanli85** [comment]
sorry, forget to push the changes. Please check commit 0b3bd8c
